// Generated by Wrangler by running `wrangler types`

interface Env {
	TEST_TOKEN: string;
	POSTGRES_URL: string;
	HATCHET_CLIENT_TOKEN: string;
	BASELIME_API_TOKEN: string;
	TEST_CLERK_API_TOKEN: string;
	TEST_STRIPE_API_TOKEN: string;
	isDev: string;
	CLERK_SECRET_KEY: string;
	CLERK_PUBLISHABLE_KEY: string;
	COLLECTION_SYNC_WORKFLOW: Workflow;
}
