#:schema node_modules/wrangler/config-schema.json
name = "hazel-cf"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[workflows]]
name = "resource-sync-workflow"
binding = "RESOURCE_SYNC_WORKFLOW"
class_name = "ResourceSyncWorkflow"


[vars]
isDev = true


# [[workflows]]
# name = "second-workflow"
# binding = "SECOND_WORKFLOW"
# class_name = "SecondWorkflow"
